/**
 * Gizlilik politikası ve kullanım şartları metinleri – ConsentGateScreen ve modal içeriği için.
 */
export const PRIVACY_SECTIONS = [
  { title: '1. Introduction', body: 'MYKBS is a hospitality compliance and identity verification application developed and operated by LITXTECH LLC.\n\nThe application is designed to help accommodation providers manage legally required guest identity registrations and transmit necessary information to official systems where required by law.\n\nLITXTECH LLC respects the privacy of users and is committed to protecting personal data in accordance with applicable laws and platform policies.\n\nThis Privacy Policy explains what information we collect, how it is used, and how it is protected.' },
  { title: '2. Information We Collect', body: 'MYKBS may process the following categories of information:\n\nIdentity Information\nWhen accommodation providers register guests as required by local regulations, the following information may be processed: Full name; National ID or passport number; Date of birth; Nationality; Passport or ID document data (including MRZ data when scanned).\n\nContact Information\nIf provided by the accommodation provider: Phone number; Email address.\n\nBusiness Information\nFor registered accommodation businesses: Business name; Branch information; KBS registration codes or facility identifiers.\n\nDevice Information\nTo ensure system security and stability, limited technical data may be collected: Device model; Operating system version; Application version; Error logs. This information is used solely for system reliability and security.' },
  { title: '3. How We Use the Information', body: 'Information collected through MYKBS is used for the following purposes: Recording guest identity information required by hospitality regulations; Submitting legally required notifications to official systems when applicable; Managing accommodation branch records; Ensuring system security and preventing misuse; Improving application stability and performance.\n\nLITXTECH LLC does not sell or rent personal data to third parties.' },
  { title: '4. Legal Basis for Processing', body: 'Personal data processed within MYKBS may be required to comply with local hospitality and identity reporting regulations applicable to accommodation providers. The application functions as a technical platform that enables businesses to fulfill their legal reporting obligations.' },
  { title: '5. Data Storage and Security', body: 'LITXTECH LLC implements industry-standard technical and organizational measures to protect data against unauthorized access, alteration, disclosure, or destruction. These measures include: Encrypted communication (HTTPS); Secure infrastructure; Access control systems; Logging and monitoring. Only authorized systems and services may access stored data.' },
  { title: '6. Data Sharing', body: 'Personal data may be shared only in the following situations: With official government systems when legally required by hospitality regulations; With service providers that support infrastructure, hosting, or security operations under strict confidentiality obligations. No personal data is shared for advertising or marketing purposes.' },
  { title: '7. Data Retention', body: 'Personal data is retained only for as long as necessary to fulfill legal obligations and operational requirements of the hospitality reporting system. Retention periods may vary depending on applicable legal requirements.' },
  { title: '8. User Rights', body: 'Depending on applicable laws, individuals may have the right to: Request access to their personal data; Request correction of inaccurate information; Request deletion where legally permitted; Request information about how their data is processed. Requests may be submitted using the contact information below.' },
  { title: '9. Children\'s Privacy', body: 'MYKBS is designed for use by registered accommodation businesses and authorized staff members. The application is not intended for use by children.' },
  { title: '10. Changes to This Policy', body: 'LITXTECH LLC may update this Privacy Policy from time to time to reflect operational or legal changes. Updated versions will be published within the application or associated websites.' },
  { title: '11. Contact Information', body: 'If you have any questions regarding this Privacy Policy, you may contact:\n\nLITXTECH LLC\nEmail: support@litxtech.com' },
];

export const TERMS_SECTIONS = [
  { title: '1. Acceptance of Terms', body: 'These Terms of Service govern the use of the MYKBS application, operated by LITXTECH LLC.\n\nBy accessing or using the MYKBS application, you agree to comply with these Terms.\n\nIf you do not agree with these Terms, you must not use the application.' },
  { title: '2. Description of the Service', body: 'MYKBS is a hospitality compliance and identity verification platform designed to assist accommodation providers in managing guest identity records and transmitting legally required information to official reporting systems where applicable.\n\nThe application provides tools for: Guest identity registration; Passport or ID scanning; Branch management for accommodation businesses; Transmission of legally required reporting data.\n\nMYKBS functions as a technical platform that helps accommodation providers manage compliance processes.' },
  { title: '3. Eligible Users', body: 'The MYKBS application is intended for use by: Licensed accommodation providers; Authorized hotel or lodging staff; Businesses required to comply with guest identity reporting regulations.\n\nUsers must have the legal authority to process and submit guest information within their organization.' },
  { title: '4. User Responsibilities', body: 'Users agree that they will: Use the application only for lawful purposes; Enter accurate and legitimate guest information; Comply with all applicable hospitality and identity reporting regulations; Protect access credentials and prevent unauthorized access.\n\nUsers are responsible for ensuring that guest information entered into the system is accurate and lawfully collected.' },
  { title: '5. Legal Compliance', body: 'MYKBS is designed to support accommodation providers in fulfilling legal reporting obligations. However, LITXTECH LLC is not responsible for ensuring that a business complies with local laws or regulations. Each accommodation provider is responsible for complying with all applicable legal requirements.' },
  { title: '6. Data Processing', body: 'The application may process personal data including guest identity information as part of legally required reporting processes. Data processing is conducted in accordance with the MYKBS Privacy Policy. Users agree that they have the legal authority to process and submit guest information through the application.' },
  { title: '7. Service Availability', body: 'LITXTECH LLC strives to maintain reliable system availability but does not guarantee uninterrupted access to the MYKBS service. Temporary interruptions may occur due to: System maintenance; Infrastructure issues; Third-party service outages; Network conditions.' },
  { title: '8. Limitation of Liability', body: 'To the maximum extent permitted by law, LITXTECH LLC shall not be liable for: Incorrect information submitted by users; Legal penalties incurred due to misuse of the system; Loss of data caused by user error; Service interruptions beyond reasonable control. Users are responsible for verifying information before submission.' },
  { title: '9. Account Security', body: 'Users are responsible for maintaining the confidentiality of their account credentials. Any activity conducted through a user account is the responsibility of the account holder. Users must immediately notify LITXTECH LLC if unauthorized access is suspected.' },
  { title: '10. Intellectual Property', body: 'All software, design, systems, and technology related to the MYKBS application are the intellectual property of LITXTECH LLC. Users may not: Reverse engineer the application; Copy or redistribute the software; Attempt to bypass security mechanisms.' },
  { title: '11. Termination', body: 'LITXTECH LLC reserves the right to suspend or terminate accounts that: Violate these Terms; Attempt to misuse the platform; Engage in unlawful activities. Users may discontinue use of the application at any time.' },
  { title: '12. Modifications to the Terms', body: 'LITXTECH LLC may update these Terms from time to time. Updated versions will be published within the application or official service channels. Continued use of the application after updates constitutes acceptance of the revised Terms.' },
  { title: '13. Governing Law', body: 'These Terms shall be governed by and interpreted in accordance with the applicable laws governing the operations of LITXTECH LLC.' },
  { title: '14. Contact', body: 'For questions regarding these Terms of Service:\n\nLITXTECH LLC\nEmail: support@litxtech.com' },
];
